### ISSUE TITLE
Missing file shrpy.db

### ISSUE THREAD

**Issue by DonkeyBlaster** [vremes/shrpy#36]
When following the instructions for setting up production in the README, gunicorn raises `sqlite3.OperationalError: unable to open database file`. This repo does not contain a shrpy.db, which I assume is required for the application. I do see a `CREATE TABLE IF NOT EXISTS` in utils.py though, maybe add an empty .db file to the repo or add a note in the README to create one?

**Comment by vremes** [comment]
Hey there,

`sqlite3.connect(...)` should create the database file, if it does not exist already.

https://github.com/vremes/shrpy/blob/ce9dd1453679912f238c0c5054208b3744ac9a52/app/core/utils.py#L81

To me it sounds like this could be a permission issue and that is why gunicorn is unable to access/open the database file.

I will test and see if i'm able to reproduce this issue.

**Comment by vremes** [comment]
I tested this on Ubuntu 20.04.3 using Python 3.8.10 and got this error:
```
sqlite3.OperationalError: attempt to write a readonly database
```
However, i fixed it by changing the ownership of `/var/www/shrpy/` directory using `chown` to the user which was running gunicorn.

**Comment by DonkeyBlaster** [comment]
Hi,
Thanks for the follow up. I believe you were correct in that it is a permission error. I got my install working by using gunicorn and python bins from a virtualenv in the /var/www/shrpy/ folder.
